name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLA:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read and signed the CLA. Thank you!') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '.github/signatures/version1/cla.json'
          path-to-document: 'https://github.com/KelvinCosta/pokerHandExtractor/blob/master/CONTRIBUTING.md'
          branch: 'master'
          allowlist: 'bot*'
          custom-notsigned-prcomment: '👋 Thank you for your contribution! To keep our project sustainable, we need you to accept our dual-licensing terms outlined in our `CONTRIBUTING.md` file.<br/><br/>Please sign the CLA by leaving a comment **exactly** with the text below in this PR:<br/><br/>`I have read and signed the CLA. Thank you!`'
          custom-pr-sign-comment: 'I have read and signed the CLA. Thank you!'
